---
title: "Desigualdad y PP"
author: "Sivi"
format: html
editor: visual
bibliography: desigualdad-pp.bib
link-citations: true 
---

# "Tendencias de Desigualdad y Participación Política: Estudiantes Universitarios en Chile"

En el Chile actual, la desigualdad social y la estratificación económica han emergido como temas con una alta relevancia sociológica. Estas dinámicas sociales plantean desafíos significativos para la cohesión social y la justicia distributiva en las sociedades modernas. La percepción de la desigualdad desempeña un rol crucial en la configuración de actitudes y comportamientos sociales y políticos de los individuos.

La educación cívica y la política educativa se presentan como herramientas fundamentaes para abordar esta problemática. En ese contexto, comprender la relación entre la percepción de la desigualdad, la educación cívica y la participación política de estudiantes universitarios adquiere una relevancia particular.

En este estudio, se propone analizar cómo la percepción de la desigualdad social influye en la participación política de los estudiantes universitarios en Chile. Diversos estudios indican que la participación política demuestra una clara relación con el estatus socioeconómico, aquellos que tienen un nivel socioeconómico más alto, tienen una mayor probabilidad de involucrarse en el sistema político. [@castilloSocialInequalityChanges2014]
